[package]
name = "hirola"
version = "0.1.3-alpha.0"
authors = ["Geoffrey Mureithi <mureithinjuguna@gmail.com>"]
description = "An html library for building client side webapps"
repository = "https://github.com/geofmureithi/hirola"
documentation = "https://docs.rs/hirola"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["wasm", "html", "dom", "web"]
edition = "2018"

[dependencies]
hirola-core = { path = "crates/hirola-core", version = "0.1.3-alpha.0" }
hirola-macros = { path = "crates/hirola-macros", version = "0.1.0" }

[workspace]
members = [
    "crates/hirola-core",
    "crates/hirola-macros",
    "examples/counter",
]
