[package]
name = "counter"
version = "0.1.3-alpha.0"
authors = ["Geoffrey Mureithi <mureithinjuguna@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
hirola = { path = "../../" }
typed-html = { git = "https://github.com/bodil/typed-html", rev = "4c13ecca" }
console_error_panic_hook = "0.1"
log = "0.4"
console_log = "0.2"
wasm-bindgen = "0.2.48"
