[package]
name = "hirola-core"
version = "0.1.3-alpha.0"
authors = ["Geoffrey Mureithi <mureithinjuguna@gmail.com>"]
edition = "2018"
description = "An html library for building client side webapps"
repository = "https://github.com/geofmureithi/hirola"
documentation = "https://docs.rs/hirola"
readme = "../../README.md"
license = "MIT OR Apache-2.0"
keywords = ["wasm", "html", "dom", "web"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_error_panic_hook = "0.1.5"
dominator = "0.5.0"
wasm-bindgen = "0.2.48"
futures-signals = "0.3.0"
typed-html = { git = "https://github.com/bodil/typed-html", rev = "4c13ecca", version = "0.2.2" }
typed-html-macros = "0.2.2"
web-sys = "0.3"
